### ISSUE TITLE
Android text editing options are not displayed properly

### ISSUE THREAD

**Issue by bsurd** [mozilla-lockwise/lockwise-android#363]
## Steps to reproduce
1. Open Lockbox and tap on Get Started.
2. Write anything in the email field.
3. Long tap to select the text.

### Expected behaviour
Everything looks as expected.

### Actual behaviour
The text selection options box is not properly displayed.

### Device and build information
- Sony Xperia Z5 Premium (Android 7.1.1)
- Samsung Galaxy S8 (Android 8)
- Google Pixel (Android 9)
- [Build #2068](https://app.bitrise.io/build/5de084abff2a9e31)

### Notes
- Paste and selection handlers are also not displayed properly.
- [Logcat](https://github.com/mozilla-lockbox/lockbox-android/files/2740954/log.txt)
- [Video](https://drive.google.com/open?id=1_gRrJKRTEwyrI_I-dUyAliMyza8OqOzs)

**Comment by sashei** [comment]
I don't know if this is something we control; the email field is part of the FxA login webpage.

**Comment by diegolucasb** [comment]
It happens because you are using WebView component. It has some kind of limitation that isn't able to render selection popup properly. 

I did a quick test using [Chrome Custom Tabs](https://developer.chrome.com/multidevice/android/customtabs), which I believe is more appropriate for this `FxALogin` case, and it behaviors as expected as you can see in image below.

If you guys don't mind using Chrome tabs, I'd like to help you with this issue!

<img src="https://user-images.githubusercontent.com/4621339/51359045-11b13000-1aad-11e9-9579-b338e4d0d91d.png" width="480">

**Comment by sashei** [comment]
@diegolucasb if you can retain the styling, you're more than welcome to make a PR! Thanks for looking into this :)

**Comment by diegolucasb** [comment]
Great @sashei! I'm gonna work on this!

**Comment by eliserichards** [comment]
Closing as this is no longer applicable.
