### ISSUE TITLE
The Email is changed when returning from "Reset password" screen

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#443]
## Steps to reproduce
1. Install and launch Lockbox.
2. Tap on "Get Started" and the enter your email.
3. Tap on **`Forgot password?`**
4. Type anything on the **`Email`** field.
5. Tap on the **`Remember password? Sign in`.**

### Expected behavior
The email should remain the same, as was before tapping on the **`Forgot password?`**
### Actual behavior
After tapping on the **`Remember password? Sign in`** the user is redirected to **`Enter your email`** screen and the email address/text is changed.
### Device information
* Firefox Lockbox version: 1.0 [build #2561](https://app.bitrise.io/build/8e95ac67b65f0d76)
* Samsung Galaxy Note 9(Android 8.1.0)
* Google Pixel 3 XL (Android P/9)

### Notes
Note that no matter what you type, the text is changed automatically on the `Email` field.
Even tho the **`Begin reset`** button is not touched the email still changes.
[Video](https://drive.google.com/file/d/1whs7BtoNq3WwiKU3Oyx7XmeIJQ5kB55L/view?usp=sharing)
[logcat.txt](https://github.com/mozilla-lockbox/lockbox-android/files/2869625/logcat.txt)

**Comment by linuxwolf** [comment]
Thanks for the report, @abodea.

The content comes from the FxA; including @stomlinson / @vladikoff for their edification and insights.

**Comment by shane-tomlinson** [comment]
This is intentional behavior, edits in the email field are propagated to other screens, e.g., changing the email on /signin is reflected in /signup and vice versa. Changes in /reset_password are reflected back to /signin, but not /signin to /reset_password. 

Because resetting a password can cause a user to lose Sync data, we make the user enter their email address to give them a moment's pause to be really sure they want to continue.

**Comment by eliserichards** [comment]
Closing as invalid based on Shane's comment.
