### ISSUE TITLE
App syncs every time it's brought to the foreground

### ISSUE THREAD

**Issue by agi90** [mozilla-lockwise/lockwise-android#735]
On my phone, Lockwise syncs whenever the app is brought to the foreground, which makes it very hard to use (especially on a slow connection). Right now it even syncs when the screen turns off and on.

I'm not totally sure if this is the intended behavior or if I hit a bug but I'm happy to add whatever debugging information you might need.

Phone: Samsung S10e
Version: Latest from playstore (6/4)

**Comment by devinreams** [comment]
Quick triage: currently by-design but high frequency, but not a great user experience (medium impact). Assigning P2.

Can fairly easily check and see if synced in the past X minutes, because users can still manually force a sync.

Can also consider ways to make the UI/UX available and responsive so as to not block the user.

**Comment by changecourse** [comment]
I'd like to pose a one-time, 24hr default timer for automatically syncing, since we also have the ability for someone to trigger a manual sync if needed. 

There would also be some good improvements to make around caching/storing logins for instances when sync fails, so access can still be available for 'last-synced' logins, but that's a separate issue.

**Comment by faogustavo** [comment]
If we opt for the "delay" strategy, I think we should also add a new parameter in the settings screen. In this way, the user can manage the delay interval.

**Comment by sashei** [comment]
@changecourse I'm making an assumption here that we should differentiate the manual sync and the auto sync in that performing a manual sync will _not_ change the next automatic sync time. what's your feeling about that? should manually syncing push back the next automatic sync time?

**Comment by changecourse** [comment]
@sashei That's an interesting question... I could go either way, but my initial take would be that a manual sync would reset the timer.

**Comment by sashei** [comment]
@faogustavo that's a good suggestion; I think it's out of scope for this ticket but I've made a follow-up one: #747

**Comment by agi90** [comment]
Thanks for fixing this!
