### ISSUE TITLE
IllegalStateException: syncConfig should already be defined

### ISSUE THREAD

**Issue by yuvalwolf** [mozilla-lockwise/lockwise-android#803]
[Sentry issue #5984172](https://sentry.prod.mozaws.net/operations/lockwise-android/issues/5984172)

High number of IllegalStateExceptions raised for users running v1.1.2.

### Device & build information
* Device: Seems to be affecting all Android devices running v1.1.2
* Build version: 1.1.2
### Notes
```
llegalStateException: syncConfig should already be defined
    at h.c.h.F.e(DataStore.kt:11)
    at h.c.h.F.l(DataStore.kt:4)
    at h.c.h.A.accept(DataStore.kt:3)
    at d.a.e.d.g.a(LambdaObserver.java:7)
    at c.g.b.d$d.a(ReplayRelay.java:21)
...
(24 additional frame(s) were not displayed)

syncConfig should already be defined
```

**Comment by eliserichards** [comment]
This crash didn't exist before June 24 because that's when we released our PR with mitigations for the "datastore backend not set" failure. This error message, `"syncConfig should already be defined"` is being received because we are attempting to sync and the `SyncUnlockInfo` is null (possibly corrupted in some way?). This is why we are seeing so many sync timeout toasts.

**Comment by eliserichards** [comment]
Closing in favor of #810 investigation.
